### ISSUE TITLE
Failed to run with npx

### ISSUE THREAD

**Issue by OmgImAlexis** [franciscop/check-licenses#1]
```
> npx check-licenses
npx: installed 71 in 10.933s
Error: Cannot convert undefined or null to object
```

Tried on Windows 11 with `npx@6.14.15`

**Comment by franciscop** [comment]
If you do `ls` does `package-lock.json` show up? `check-licenses` is using that to determine the project licenses, while if you want a more general checker (but also slower and with some minor hiccups) you can try instead `legally`.

**Comment by franciscop** [comment]
I just published `check-licenses@1.01`, could you please try again and see if it gives you the same error (or a new one?)? Do you get any other output in the terminal besides what you showed me?

**Comment by OmgImAlexis** [comment]
Yes. Tried legally and it worked without any issues. 

I’ll try the new version when I get a chance.

**Comment by franciscop** [comment]
Cool, thanks!

**Comment by franciscop** [comment]
It seems like a npm@6 vs npm@7 issue:

https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json#lockfileversion

Unfortunately I'm going to suggest upgrading to npm@7 or higher (current version is 8) since I do not have the bandwidth to support older versions (recommended), or to use `legally` instead (not recommended).
