### ISSUE TITLE
Add pnpm support

### ISSUE THREAD

**Issue by ai** [franciscop/check-licenses#2]
Can we add `pnpm-lock.yml` file support?

**Comment by franciscop** [comment]
Oh hey @ai, love nanoid!

Reading [about pnpm motivation](https://pnpm.io/motivation) a bit, it seems it's based on some old optimization over how npm used to work:

![image](https://user-images.githubusercontent.com/2801252/163664460-81d4fc4a-b748-400d-80f2-3fd6d642a29e.png)

However now npm dedupes their dependencies similarly to what pnpm claims, so is pnpm still useful?

<img width="461" alt="image" src="https://user-images.githubusercontent.com/2801252/163664699-f9865585-46ea-4208-bbf7-8e2b78395bad.png">

**Comment by franciscop** [comment]
Update: there doesn't seem to be a decent way of finding the resolved path from the `pnpm-lock.yml` file, besides actually crawling through the filesystem and doing a bunch of checks (LICENSE vs LICENSE.txt vs LICENSE.md is another topic).

See on here, on the right both highlighted packages have a "dependencies" key, but in "domexception" its dependency is resolved to the "node_modules" subfolder (on the top left), while in "end-of-stream" its dependency is resolved to the top-level node_modules folder:

<img width="779" alt="Screen Shot 2022-04-16 at 16 18 50" src="https://user-images.githubusercontent.com/2801252/163665890-42f7e568-3225-4a9b-a002-59ca5d4f4650.png">

On the global scope the two versions of `webidl-conversions` are presented just like this, without specifying their path (one is in the top level, another is in a sub-sub-folder):

<img width="442" alt="image" src="https://user-images.githubusercontent.com/2801252/163666113-163faf1a-40c0-4563-948c-183e04e4f968.png">

I'm not about to start to do manual filesystem checks, I tried in [this other license checker](https://github.com/franciscop/legally) and it became a huge mess, so I gave up on the filesystem and now only deal with sane lock files where I can explicitly find out where the file is. On the other hand, you can check [that other license checker](https://github.com/franciscop/legally) since it works just with the `node_modules` folder and subfiles, so while not as precise* as check-licenses it'll work with any file manager that uses `node_modules`.

*It suffers from _overfetching_ licenses found in node_modules, so it's on the safe side.

**Comment by ai** [comment]
pnpm is still very useful since npm doesn't have symlink `node_modules` model.

npm is now using old Yarn way with dedublication which is less effective than symlink model.

**Comment by franciscop** [comment]
Thanks for the follow up! The issue of not specifying paths to resolve from the `pnpm-lock.yml` file is a major issue and the blocker here, not going to do manual folder resolution in this library.
